//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Entity
{
	using Newtonsoft.Json;
	using System;
	public partial class HinhAnhSP
    {
        public int Id_HA { get; set; }
        public Nullable<int> Id { get; set; }
        public string DiaChi { get; set; }
		public virtual SanPham SanPham { get; set; }
    }
}
