//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.HoaDonSanPhams = new HashSet<HoaDonSanPham>();
        }
    
        public int Id_HoaDon { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string DienThoai { get; set; }
        public int fax { get; set; }
        public string Cty { get; set; }
        public System.DateTime NgayDat { get; set; }
    
        public virtual ICollection<HoaDonSanPham> HoaDonSanPhams { get; set; }
    }
}
