//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Entity
{
	using Newtonsoft.Json;
	using System;
	using System.Collections.Generic;

	public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.HinhAnhSPs = new HashSet<HinhAnhSP>();
            this.HoaDonSanPhams = new HashSet<HoaDonSanPham>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_Loai { get; set; }
        public string TenSp { get; set; }
        public string MauMuc { get; set; }
        public string KichThuoc { get; set; }
        public int Gia { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		[JsonIgnore]
		public virtual ICollection<HinhAnhSP> HinhAnhSPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		[JsonIgnore]
		public virtual ICollection<HoaDonSanPham> HoaDonSanPhams { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
